base.ssh: &base.ssh
  stage: ---
  hostname: ""
  port: 22
  user: ec2-user
  group: nginx

develop.akachan:
  <<: *base.ssh
  hostname: akachan
  stage: develop
  port: 22
  deploy_path: /var/www/html
  branch: master
  project_root: /

develop.akachan_dev2:
  <<: *base.ssh
  hostname: akachan_dev2
  stage: develop
  port: 22
  deploy_path: /var/www/html
  branch: master
  project_root: /
